### ISSUE TITLE
Official ansible-lint action

### ISSUE THREAD

**Issue by webknjaz** [stoe/actions#2]
Hi,

I'm going to merge your `ansible-lint` action to the official repo so that it'd be centralized. JFYI.

**Comment by stoe** [comment]
Hi @webknjaz. 

Anything I can do?

**Comment by webknjaz** [comment]
I invite you to collaborate in ansible/ansible-lint repo :)

**Comment by webknjaz** [comment]
Closing as per https://github.com/stoe/actions/commit/b48c994919acd5a283b4bfbb60c69bca771f8395#commitcomment-32725937. Thanks for the initial Action and I hope to see you around :)

P.S. I've added it to Marketplace @ https://github.com/marketplace/actions/ansible-lint but it seems like some people see 404 at this address (for unknown reason). The source is @ https://github.com/ansible/ansible-lint-action now.
